name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
    - name: Install dependencies
      run: npm install learnyounode
    - run: npm ci
    - run: learnyounode
    - name: Run tests
      run: test hello-world.js
    - run: test baby-steps.js
    - run: test my-first-io.js
    - run: test my-first-async-io.js
    - run: test filtered-ls.js
    - run: test make-it-modular.js
